TuJoseo/Controllers/JoseosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using TuJoseo.Models;

namespace TuJoseo.Controllers
{
    public class JoseosController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly string ConnectionString;

        public JoseosController(IConfiguration configuration)
        {
            _configuration = configuration;
            ConnectionString = _configuration.GetConnectionString("DB");
        }

        //Buscar Joseador
        public IActionResult Index(string? search)
        {
            string userID = "";
            try
            {
                userID = TempData["UserID"].ToString();
            }
            catch
            {
                userID = SetCoockie();
            }

            TempData["UserID"] = SetCoockie().ToString();

            JoseoAndTypesModel joseosAndTypes = new JoseoAndTypesModel();
            List<UserModel> users = new List<UserModel>();
            List<CategoryModel> categories = new List<CategoryModel>();

            string query = "";
            /******************************************************************************/
            //Sin busqueda
            if (search == null)
                query = "SELECT UserID, UserRol, UserName, UserHabilities, UserLocation, UserPhone, UserJoseosRealized, UserJobQuality, UserSimpaty " +
            "FROM [TuJoseoDB].[dbo].[UserTable] " +
            $"WHERE UserID != '{userID}';";
            //Buscar por ID
            else
            {
                try
                {
                    TempData["UserID"] = userID;

                    Convert.ToInt32(search);
                    query = @$"SELECT UserID, UserRol, UserName, UserHabilities, UserLocation, UserPhone, UserJoseosRealized, UserJobQuality, UserSimpaty " +
                $"FROM [TuJoseoDB].[dbo].[UserTable] " +
                $"WHERE CategoryUserID = '{search}' AND UserID != '{userID}';";

                }
                catch (Exception)
                {
                    TempData["UserID"] = userID;

                    query = @$"SELECT UserID, UserRol, UserName, UserHabilities, UserLocation, UserPhone, UserJoseosRealized, UserJobQuality, UserSimpaty " +
                 $"FROM [TuJoseoDB].[dbo].[UserTable] " +
                 $"WHERE LOWER(UserName) LIKE '%{search.ToLower()}%' AND UserID != '{userID}';";
                }
            }

            using (SqlConnection con = new SqlConnection(ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    con.Open();
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                UserModel user = new UserModel()
                                {
                                    UserID = reader.GetInt32(0),
                                    UserRol = reader.GetString(1),
                                    UserName = reader.GetString(2),
                                    UserHabilities = reader.GetString(3),
                                    UserLocation = reader.GetString(4),
                                    UserPhone = reader.GetString(5),
                                    UserJoseosRealized = reader.GetInt32(6),
                                    UserJobQuality = reader.GetInt32(7),
                                    UserSimpaty = reader.GetInt32(8),
                                };

                                users.Add(user);
                            }

                            TempData["UserID"] = userID;
                            TempData["UserID"] = SetCoockie().ToString();

                        }
                    }
                }
            }

            string queryTypes = $@"Select * From CategoryUserTable";
            using (SqlConnection con = new SqlConnection(ConnectionString))
            {
                con.Open();
                using (SqlCommand cmd = new SqlCommand(queryTypes, con))
                {
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                CategoryModel category = new CategoryModel()
                                {
                                    ID = reader.GetInt32(0),
                                    Name = reader.GetString(1),
                                };

                                categories.Add(category);
                            }
                            TempData["UserID"] = userID;
                            TempData["UserID"] = SetCoockie().ToString();

                        }
                    }
                }
            }

            joseosAndTypes.Users = users;
            joseosAndTypes.Categories = categories;

            TempData["UserID"] = userID;
            TempData["UserID"] = SetCoockie().ToString();

            return View(joseosAndTypes);
        }

        public IActionResult SearchJoseo(string? search)
        {
            string userID = SetCoockie();
            TempData["UserID"] = SetCoockie().ToString();

            List<JoseoModel> joseos = new List<JoseoModel>();
            string query = "";

            if (string.IsNullOrEmpty(search))
            {
                query = @$"SELECT * FROM JoseosTable WHERE JoseadorRealID IS NULL AND JoseadorID != '{userID}';";
            }
            else
            {
                query = @$"SELECT * FROM JoseosTable WHERE JoseadorRealID IS NULL AND JoseadorID != '{userID}' AND (JoseoTitle LIKE '%{search}%' OR JoseoDescription LIKE '%{search}%');";
            }

            using (SqlConnection con = new SqlConnection(ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand(query, con))
                {
                    con.Open();
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                JoseoModel joseo = new JoseoModel()
                                {
                                    JoseoID = reader.GetInt32(0),
                                    JoseoTitle = reader.GetString(1),
                                    JoseoDescription = reader.GetString(2),
                                    JoseoPrice = reader.GetString(3),
                                    JoseadorID = reader.GetString(4)
                                };

                                joseos.Add(joseo);
                            }
                        }
                    }
                }
            }

            TempData["UserID"] = userID;
            TempData["UserID"] = SetCoockie().ToString();

            return View(joseos);
        }


        public IActionResult SearchOwnJoseo()
        {
            string userID = SetCoockie();
            TempData["UserID"] = SetCoockie().ToString();

            List<JoseoModel> joseos = new List<JoseoModel>();
            MainOwnJoseoModel mainOwnJoseoModel = new MainOwnJoseoModel()
            {
                MisJoseos = new List<JoseoModel>(),
                JoseosCreados = new List<JoseoModel>()
            };

            string queryMisJoseos = @$"SELECT JoseosTable.*, UserTable.UserCompleteName AS UserName
FROM JoseosTable
INNER JOIN UserTable ON UserTable.UserID = JoseosTable.JoseadorRealID
WHERE JoseosTable.JoseadorRealID = {userID};";

            using (SqlConnection con = new SqlConnection(ConnectionString))
            {
                using (SqlCommand cmd = new SqlCommand(queryMisJoseos, con))
                {
                    con.Open();
                    using (SqlDataReader reader = cmd.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())
                            {
                                JoseoModel joseo = new JoseoModel()
                                {
                                    JoseoID = reader.GetInt32(0),
                                    JoseoTitle = reader.GetString(1),
                                    JoseoDescription = reader.GetString(2),
                                    JoseoPrice = reader.GetString(3),
                                    JoseadorID = reader.GetString(4),
                                    JoseadorRealID = reader.GetString(10),
                                    JoseadorRealName = reader.GetString(11),
                                };

                                joseos.Add(joseo);
                            }
                            mainOwnJoseoModel.MisJoseos = joseos;
                        }
                    }
                }
            }

            List<JoseoModel> joseoscreado = new List<JoseoModel>();

            string queryJoseosCreados = @$"SELECT JoseosTable.*, UserTable.UserCompleteName AS UserName
FROM JoseosTable
LEFT JOIN UserTable ON UserTable.UserID = JoseosTable.JoseadorRealID
WHERE JoseosTable.JoseadorID = {userID};";

            using (SqlConnection concreado = new SqlConnection(ConnectionString))
            {
                using (SqlCommand cmdcreado = new SqlCommand(queryJoseosCreados, concreado))
                {
                    concreado.Open();
                    using (SqlDataReader reader = cmdcreado.ExecuteReader())
                    {
                        if (reader.HasRows)
                        {
                            while (reader.Read())

TuJoseo/Views/Joseos/CreateJoseo.cshtml
@model CreateJoseoModel

@{
    bool creando = (string.IsNullOrEmpty(Model.JoseoTitle));
    string mode = creando ? "crear" : "editar";
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Crear Joseo</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <section class="content">
                <div class="row">
                    <div class="col-md-6">
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">General</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                @if (mode == "crear")
                                {
                                    <div class="form-group">
                                        <label for="joseoTitle">Nombre del proyecto</label>
                                        <input type="text" id="joseoTitle" class="form-control" asp-for="JoseoTitle">
                                    </div>
                                }
                                else
                                {
                                    <div class="form-group">
                                        <label for="joseoTitle">Nombre del proyecto</label>
                                        <input type="text" id="joseoTitle" class="form-control" asp-for="JoseoTitle" disabled>
                                    </div>
                                }
                                <div class="form-group">
                                    <label for="joseoDescription">Descripción del proyecto</label>
                                    <textarea id="joseoDescription" class="form-control" rows="4" asp-for="JoseoDescription"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="joseoStatus">Estado</label>
                                    <select id="joseoStatus" class="form-control custom-select" asp-for="JoseoStatus">
                                        <option selected disabled>Seleccione uno</option>
                                        <option>Desde cero</option>
                                        <option>Idea base</option>
                                        <option>En proceso</option>
                                        <option>Buscando ideas</option>
                                        <option>Buscando personal</option>
                                        <option>Casi terminado</option>
                                        <option>Toques finales</option>
                                        <option>Terminado</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="inputClientCompany">Compañía</label>
                                    <input type="text" id="inputClientCompany" class="form-control">
                                </div>
                                <div class="form-group">
                                    <label for="joseadorID" hidden>Líder del proyecto</label>
                                    <input type="text" id="joseadorID" class="form-control" hidden value="@TempData["UserID"]">
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->
                    </div>
                    <div class="col-md-6">
                        <div class="card card-secondary">
                            <div class="card-header">
                                <h3 class="card-title">Presupuesto$ (en DOP)</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="joseoPrice">Presupuesto estimado</label>
                                    <input type="number" id="joseoPrice" class="form-control" asp-for="JoseoPrice">
                                </div>
                                <div class="form-group">
                                    <label for="joseoEstimatedTime">Duración estimada del proyecto (seleccionar fecha final)</label>
                                    <input type="date" id="joseoEstimatedTime" class="form-control" asp-for="JoseoEstimatedTime">
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                        <!-- /.card -->

                        <div class="card card-secondary">
                            <div class="card-header">
                                <h3 class="card-title">Términos y condiciones</h3>

                                <div class="card-tools">
                                    <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                                        <i class="fas fa-minus"></i>
                                    </button>
                                </div>
                            </div>
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="inputEstimatedBudget">Lea aténtamente</label>
                                    <p>
                                        1. REQUISITOS RELATIVOS AL USUARIO
                                        El Sitio Web y los servicios relacionados con el mismo se ofrecen a los Usuarios que tengan capacidad legal para otorgar contratos legalmente vinculantes según la legislación aplicable.
                                        Los menores no están autorizados para utilizar el Sitio Web. Si usted es menor de edad, por favor, no utilice esta web.
                                    </p>
                                    <label for="inputEstimatedBudget">Al continuar usando esta web acepta explícitamente los términos y condiciones puestos tanto por su empleador cómo la página web, en caso de ser el empleador también acepta los términos de su empleado.</label>
                                </div>
                            </div>
                            <!-- /.card-body -->
                        </div>
                    </div>
                </div>
                <form id="joseoForm" method="post">
                    <div class="row">
                        <div class="col-12">
                            <a href="@Url.Action("Index", "Home")" class="btn btn-secondary">Cancelar</a>
                            @if (mode == "crear")
                            {
                                <input href="@Url.Action("Index", "Home")" id="btnSaveJoseo" value="Crear Nuevo Joseo" class="btn btn-success float-right">
                            }
                            else
                            {
                                <input href="@Url.Action("Index", "Home")" id="btnSaveJoseo" value="Guardar cambios" class="btn btn-warning float-right">
                            }
                        </div>
                    </div>
                </form>

            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    
    <script src="https://code.iconify.design/iconify-icon/1.0.7/iconify-icon.min.js"></script>
    <!-- Ajax -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>

<script>
    $(document).ready(function () {
        $("#btnSaveJoseo").click(function () {
            // Verifica el modo actual y ejecuta la función correspondiente
            if ('@mode' === 'crear') {
                saveJoseo();
            } else if ('@mode' === 'editar') {
                saveJoseoEditar();
            }
        });
    });

    function saveJoseo() {
        // Obtener valores de los controles
        var joseoTitle = $('#joseoTitle').val();
        var joseoDescription = $('#joseoDescription').val();
        var joseoStatus = $('#joseoStatus').val();
        var joseoPrice = $('#joseoPrice').val();
        var joseoEstimatedTime = $('#joseoEstimatedTime').val();
        var joseadorID = $('#joseadorID').val();

        // Construir el objeto joseo
        var joseo = {
            joseoTitle: joseoTitle,
            joseoDescription: joseoDescription,
            joseoStatus: joseoStatus,
            joseoPrice: joseoPrice,
            joseoEstimatedTime: joseoEstimatedTime,
            joseadorID: joseadorID
        };

        // Realizar la solicitud AJAX
        $.ajax({
            type: 'POST',
            url: '@Url.Action("CreateNewJoseo", "Joseos")',
            data: JSON.stringify(joseo),
            contentType: 'application/json',
            success: function (data) {
                // Manejar el éxito de la solicitud según tus necesidades
                console.log(data.message);

                // Redirigir a la página "Index" del controlador "Home"
                window.location.href = '/Joseos/SearchOwnJoseo';
            },
            error: function (error) {
                // Manejar errores si es necesario
                console.error('Error al crear el Joseo:', error.responseJSON.error);
            }
        });
    }

    function saveJoseoEditar() {
        // Obtener valores de los controles
        var joseoId = $('#joseoId').val(); // Asegúrate de tener un campo oculto que almacene el ID del joseo
        var joseoTitle = $('#joseoTitle').val();
        var joseoDescription = $('#joseoDescription').val();
        var joseoStatus = $('#joseoStatus').val();
        var joseoPrice = $('#joseoPrice').val();
        var joseoEstimatedTime = $('#joseoEstimatedTime').val();
        var joseadorID = $('#joseadorID').val();

        // Construir el objeto joseo
        var joseo = {
            joseoId: joseoId,
            joseoTitle: joseoTitle,
            joseoDescription: joseoDescription,
            joseoStatus: joseoStatus,
            joseoPrice: joseoPrice,
            joseoEstimatedTime: joseoEstimatedTime,
            joseadorID: joseadorID
        };

        // Realizar la solicitud AJAX para la edición
        $.ajax({
            type: 'POST',
            url: '@Url.Action("EditJoseo", "Joseos")',
            data: JSON.stringify(joseo),
            contentType: 'application/json',
            success: function (data) {
                console.log(data.message);

                // Redirigir a la página "Index" del controlador "Home"
                window.location.href = '/Joseos/SearchOwnJoseo';
            },
            error: function (error) {
                console.error('Error al editar el Joseo:', error.responseJSON.error);
            }
        });
    }

</script>